FROM python:3.9-slim

MAINTAINER Projekt-Microsoft

WORKDIR /app 

RUN apt update

RUN apt install ffmpeg libsm6 libxext6  -y

RUN pip install opencv-contrib-python

COPY ./extract.sh ./

RUN chmod +x extract.sh

ENTRYPOINT ["sh", "./extract.sh"]

CMD ["param1"]

#extract: docker run -i --rm -v /home/kristav/Desktop/3_letnik/Vecpredstavnost-projekt:/app extract:1.0 stegimage.png